### ISSUE TITLE
Strapi 3.6.0 breaks compatability

### ISSUE THREAD

**Issue by 0b1kn00b** [VirtusLab/strapi-plugin-comments#49]
```
ValidationError: [0] must be a `object` type, but the final value was: `[
  {
    "section": "\"plugins\"",
    "displayName": "\"Access the Comments\"",
    "uid": "\"read\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Modefation\"",
    "uid": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Single comments\"",
    "uid": "\"moderate.block.comment\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Comments threads\"",
    "uid": "\"moderate.block.thread\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Review & resolve reports\"",
    "uid": "\"moderate.reports\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  }
]`.
    at validateRegisterProviderAction (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-admin/validation/action-provider.js:77:13)
    at Object.register (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-admin/domain/action/provider.js:36:7)
    at module.exports (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-plugin-comments/config/functions/bootstrap.js:47:18)
    at execLifecycle (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:437:14)
    at /mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:447:16
    at Array.map (<anonymous>)
    at Strapi.runLifecyclesFunctions (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:444:33)
    at Strapi.load (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:379:16)
    at async Strapi.start (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:196:9)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ValidationError: [0] must be a `object` type, but the final value was: `[
  {
    "section": "\"plugins\"",
    "displayName": "\"Access the Comments\"",
    "uid": "\"read\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Modefation\"",
    "uid": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Single comments\"",
    "uid": "\"moderate.block.comment\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Comments threads\"",
    "uid": "\"moderate.block.thread\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  },
  {
    "section": "\"plugins\"",
    "displayName": "\"Review & resolve reports\"",
    "uid": "\"moderate.reports\"",
    "subCategory": "\"moderate\"",
    "pluginName": "\"comments\""
  }
]`.
    at validateRegisterProviderAction (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-admin/validation/action-provider.js:77:13)
    at Object.register (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-admin/domain/action/provider.js:36:7)
    at module.exports (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi-plugin-comments/config/functions/bootstrap.js:47:18)
    at execLifecycle (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:437:14)
    at /mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:447:16
    at Array.map (<anonymous>)
    at Strapi.runLifecyclesFunctions (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:444:33)
    at Strapi.load (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:379:16)
    at async Strapi.start (/mnt/dat/prj/vanguardia/ov8/server-strapi-deploy/node_modules/strapi/lib/Strapi.js:196:9)
^C⏎                                                                                                                         
```

**Comment by cyp3rius** [comment]
Hello @0b1kn00b,
We are working on compatibility issues with the new Strapi version.

**Comment by cyp3rius** [comment]
Hi @0b1kn00b ,

New release `1.0.1` provides compatibility with `3.6.0` version of Strapi.

**Comment by 0b1kn00b** [comment]
Thankyou gents
